const actionNames = {
  GET_CELL_TYPE_HIERARCHY: 'GET_CELL_TYPE_HIERARCHY',
  RESET_STATE: 'RESET_STATE',
  SET_SELECTED_CONCEPT: 'SET_SELECTED_CONCEPT',
  SET_DATA_TYPE: 'SET_DATA_TYPE',
  SET_ENROLLMENT_CATEGORY: 'SET_ENROLLMENT_CATEGORY',
  SET_CLUSTER: 'SET_CLUSTER',
  SET_CELL_TYPE: 'SET_CELL_TYPE',
  SET_GENE: 'SET_GENE',
  SET_ACCESSION: 'SET_ACCESSION',
  SET_SN_SWITCH: 'SET_SN_SWITCH',
  SET_SC_SWITCH: 'SET_SC_SWITCH',
  SET_NEW_CELL_CLUSTER_SWITCH: 'SET_NEW_CELL_CLUSTER_SWITCH',
  SET_ST_SWTICH: 'SET_ST_SWITCH'
};

export default actionNames;
