const actionNames = {
  GET_CELL_TYPE_HIERARCHY: 'GET_CELL_TYPE_HIERARCHY',
  RESET_STATE: 'RESET_STATE',
  SET_SELECTED_CONCEPT: 'SET_SELECTED_CONCEPT',
  SET_DATA_TYPE: 'SET_DATA_TYPE',
  SET_TISSUE_TYPE: 'SET_TISSUE_TYPE'
};

export default actionNames;
